name: Cleanup Old Artifacts

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            
            console.log(`Found ${artifacts.length} total artifacts`);
            
            // Delete all artifacts older than 1 hour
            const cutoffTime = new Date(Date.now() - 60 * 60 * 1000); // 1 hour ago
            const oldArtifacts = artifacts.filter(artifact => 
              new Date(artifact.created_at) < cutoffTime
            );
            
            console.log(`Found ${oldArtifacts.length} artifacts older than 1 hour`);
            
            for (const artifact of oldArtifacts) {
              try {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id
                });
                console.log(`✅ Deleted artifact: ${artifact.name} (${artifact.id}) - Created: ${artifact.created_at}`);
              } catch (error) {
                console.log(`❌ Failed to delete artifact ${artifact.id}: ${error.message}`);
              }
            }
            
            console.log(`Cleanup completed. Deleted ${oldArtifacts.length} artifacts.`); 